# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 48ce7ab6de834947d03a70b562b8883231c2cb68ebf7d5096dec109fc83b44d4530c84b2b2838b3c0f79aaf369d77a9a22d58e4a1b7388f2ed24d7c94a60b492

test:
  secret_key_base: 37cba5b2f99f49be847e3bb257778caba5ea3d6a1c2942b578719cdca764bbb1601610b121aff8d0aaa3fb2d0ed92f3cc338ba06539d32f8954b70e09dcf63a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
